### PR TITLE
Add arm64 support

### LINKED ISSUE #6: support arm64 architecture
https://github.com/docker-library/official-images/blob/master/library/rust   In this file I found that supprot Architectures: amd64, arm32v7, i386. So I want to know this image whether or not support arm64.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #6

### CODE REVIEW

**Comment by sfackler** [comment]
@longquan7 can you try building the Docker image on arm64 to make sure it works?

**Comment by longquan7** [comment]
@sfackler I will try building on arm64

**Comment by sfackler** [comment]
Great, thanks!

**Comment by sfackler** [comment]
https://github.com/docker-library/official-images/pull/3365

**Comment by longquan7** [comment]
@ If this image add to https://hub.docker.com/u/arm64v8/ please let me know,thanks

**Comment by sfackler** [comment]
https://hub.docker.com/r/arm64v8/rust/

**Comment by longquan7** [comment]
@sfackler OK,thanks

**Pull request merged**
